#!/usr/bin/env python3

import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning, message=".*pkg_resources.*")

import asyncio

import argparse
import logging
import logging.handlers
import socket
import signal

from sleepproxy import mdns, dnsserve, manager

class MultilineSysLogHandler(logging.handlers.SysLogHandler):
    def emit(self, record):
        lines = record.getMessage().split('\n')
        for l in lines:
           record.msg = l
           super(MultilineSysLogHandler,self).emit(record)

async def glisten(bindaddr):
    # TODO: support systemd socket activation
    logging.warning("attempting to listen for SleepProxyServer requests on UDP:[%s]:3535" % bindaddr)
    try:
        server = dnsserve.SleepProxyServer((bindaddr, 3535))
        await server.serve_forever()
    except Exception as e:
        logging.error("Failed to start server on %s:3535 - %s" % (bindaddr, e))
        raise

anyaddr = ['0.0.0.0']
if socket.has_ipv6: anyaddr.append('::')

parser = argparse.ArgumentParser(description='Sleep Proxy Server for Macs: http://github.com/kfix/SleepProxyServer')
parser.add_argument('--verbose', action='store_true', help='Run with verbose logging')
parser.add_argument('--bind', nargs='*', default=anyaddr, help='IP address[es] to listen for sleeper registrations')
args = parser.parse_args()

logfmt = 'sleepproxyd[%(process)d/%(threadName)s@%(module)s:%(levelname)s] %(message)s' #http://docs.python.org/2/library/logging.html#logrecord-attributes

if args.verbose:
    logging.basicConfig(format=logfmt + ' --(%(pathname)s:%(lineno)d)--', level=logging.DEBUG)
else:
    logging.basicConfig(format=logfmt, level=logging.WARNING)

syslog=MultilineSysLogHandler(address='/dev/log') #post messages to syslog in addition to stdout
syslog.setFormatter(logging.Formatter(logfmt))
logging.getLogger().addHandler(syslog)
#doesn't syslog exceptions...need systemd for that

async def main():
    signal.signal(signal.SIGUSR1, manager.print_hosts)
    signal.signal(signal.SIGHUP, manager.advertise)
    manager.advertise()
    
    logging.info("Attempting to bind to addresses: %s" % args.bind)
    tasks = []
    for ip in args.bind:
        try:
            task = asyncio.create_task(glisten(ip))
            tasks.append(task)
        except Exception as e:
            logging.error("Failed to create task for address %s: %s" % (ip, e))
    
    if not tasks:
        logging.error("No addresses successfully bound, exiting")
        return
        
    await asyncio.gather(*tasks, return_exceptions=True)

if __name__ == '__main__':
    asyncio.run(main())
