#!/usr/bin/env python3
#^can't run with python-dbg as scapy passes a memory pointer from python to the kernel to configure a sniffer socket, offseting the pointer ahead of the python object header's length (which is different under -dbg)...
# http://bb.secdev.org/scapy/src/2d79fea15bea69a4be1debcaf850349f0f0fb962/scapy/arch/linux.py?at=default#cl-134
# i feex
#   elif hasattr(sys, 'gettotalrefcount'): bpfh = struct.pack("HL", nb, id(bpf)+28) #python-dbg build

#substitute for sleepproxy script and dnsserve.py by bootstrapping some fake data

import os, sys
sys.path.insert(0, os.path.realpath(__file__))

import logging
import logging.handlers
logging.basicConfig(format="%(asctime)s %(levelname)s %(pathname)s:%(lineno)d %(process)d/%(threadName)s: %(message)s", level=logging.DEBUG)

import asyncio

info = {
   "othermac": "d49a20de9d39",
   "addresses": ["10.2.2.22"],
   "myif": "eth0",
   "mymac": "00:25:31:05:01:98",
   "records": []
}

from dnslib import DNSRecord, RR, TXT, PTR, SRV, A, AAAA, QTYPE

# Create fake DNS records manually with dnslib (simpler than parsing text)
fake_records = [
    RR("fakemac._device-info._tcp.local", QTYPE.TXT, ttl=4500, rdata=TXT(["model=Macmini3,1", "osxvers=13"])),
    RR("fakemac._rfb._tcp.local", QTYPE.TXT, ttl=4500, rdata=TXT("")),
    RR("_services._dns-sd._udp.local", QTYPE.PTR, ttl=4500, rdata=PTR("_rfb._tcp.local")),
    RR("_rfb._tcp.local", QTYPE.PTR, ttl=4500, rdata=PTR("fakemac._rfb._tcp.local")),
    RR("fakemac._rfb._tcp.local", QTYPE.SRV, ttl=120, rdata=SRV(0, 0, 5900, "fakemac.local")),
    RR("fakemac._ssh._tcp.local", QTYPE.TXT, ttl=4500, rdata=TXT("")),
    RR("_services._dns-sd._udp.local", QTYPE.PTR, ttl=4500, rdata=PTR("_ssh._tcp.local")),
    RR("_ssh._tcp.local", QTYPE.PTR, ttl=4500, rdata=PTR("fakemac._ssh._tcp.local")),
    RR("fakemac._ssh._tcp.local", QTYPE.SRV, ttl=120, rdata=SRV(0, 0, 22, "fakemac.local")),
    RR("22.2.2.10.in-addr.arpa", QTYPE.PTR, ttl=120, rdata=PTR("fakemac.local")),
    RR("fakemac.local", QTYPE.A, ttl=120, rdata=A("10.2.2.22")),
    RR("fakemac.local", QTYPE.AAAA, ttl=120, rdata=AAAA("fe80::d69a:20ff:fede:9d39")),
]

# Convert dnslib records to the format expected by sleepproxy
info['records'] = fake_records

import sleepproxy.manager
sleepproxy.manager.manage_host(info)

async def main():
    import signal
    
    def quit(*args):
        sleepproxy.manager.forget_host(info['othermac'])
        sys.exit()
    
    if hasattr(signal, 'SIGINFO'):  signal.signal(signal.SIGINFO, sleepproxy.manager.print_hosts) #BSD only, CTRL-T
    signal.signal(signal.SIGQUIT, sleepproxy.manager.print_hosts)
    signal.signal(signal.SIGUSR1, sleepproxy.manager.print_hosts)
    signal.signal(signal.SIGHUP, sleepproxy.manager.print_hosts) #would like to forget all hosts...
    signal.signal(signal.SIGINT, quit)
    
    logging.info('Now waiting for packets. Hit CTRL-C to quit test')
    
    # Wait forever (like signal.pause() but async)
    try:
        await asyncio.Future()  # Run forever
    except KeyboardInterrupt:
        quit()

if __name__ == '__main__':
    asyncio.run(main())
